Repository provenance-io/loan-package-contracts, pull requests merged in 2022-07, with the labels that each got.

#38 Explicitly require both owner and controller to sign for eNote updates
  contract/src/main/kotlin/io/provenance/scope/loan/contracts/UpdateENoteContract.kt
Labels: minor, chore

#39 Validate new originator ID & ULI fields during Loan recording
  buildSrc/src/main/kotlin/Dependencies.kt
  contract/src/main/kotlin/io/provenance/scope/loan/contracts/RecordLoanContract.kt
  contract/src/test/kotlin/io/provenance/scope/loan/contracts/RecordLoanContractUnitTest.kt
  contract/src/test/kotlin/io/provenance/scope/loan/test/KotestHelpers.kt
Labels: enhancement, minor

#42 Set proper workflow concurrencies
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: patch, chore

#43 Adding Figure Servicing to audiences
  build.gradle.kts
Labels: patch, chore
